// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_a(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, resultsArray, "a.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-137/problems/find-the-power-of-k-size-subarrays-i/
// https://leetcode.cn/contest/problems/find-the-power-of-k-size-subarrays-i/
