// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [A]")
	testCases := [][2]string{
		{
			`5
			6
			9 6 8 4 5 2
			4 1 5 6 3 1
			3
			4 3 2
			3 4 9
			1
			2
			1
			3
			2 3 4
			1 3 3
			12
			2 3 7 10 23 28 29 50 69 135 420 1000
			1 1 2 3 5 8 13 21 34 55 89 144`,
			`32
			0
			1
			0
			13824
			`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://codeforces.com/contest/1827/problem/A
