// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, findWinningPlayer, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-132/problems/find-the-first-player-to-win-k-games-in-a-row/
// https://leetcode.cn/problems/find-the-first-player-to-win-k-games-in-a-row/
