// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [G]")
	testCases := [][2]string{
		{
			`3
			br
			4 2
			6 2 3 7
			3 2
			4 7
			br
			5 4
			10 13 5 2 6
			2 4
			5 2
			1 5
			3 2
			br
			13 4
			769 514 336 173 181 373 519 338 985 709 729 702 168
			12 581
			6 222
			7 233
			5 117`,
			`3 4 
			4 4 2 3 
			5 6 6 5 
			`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://codeforces.com/contest/1690/problem/G
