// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc321/submit?taskScreenName=abc321_d
// 对拍：https://atcoder.jp/contests/abc321/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc321_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`2 2 7
			3 5
			6 1`,
			`24`,
		},
		{
			`1 3 2
			1
			1 1 1`,
			`6`,
		},
		{
			`7 12 25514963
			2436426 24979445 61648772 23690081 33933447 76190629 62703497
			11047202 71407775 28894325 31963982 22804784 50968417 30302156 82631932 61735902 80895728 23078537 7723857`,
			`2115597124`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc321/tasks/abc321_d
