// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc194/submit?taskScreenName=abc194_f
// 对拍：https://atcoder.jp/contests/abc194/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc194_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`10 1`,
			`15`,
		},
		{
			`FF 2`,
			`225`,
		},
		{
			`100 2`,
			`226`,
		},
		{
			`1A8FD02 4`,
			`3784674`,
		},
		{
			`DEADBEEFDEADBEEEEEEEEF 16`,
			`153954073`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc194/tasks/abc194_f
