// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_c(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, shortestDistanceAfterQueries, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-409/problems/shortest-distance-after-road-addition-queries-ii/
// https://leetcode.cn/problems/shortest-distance-after-road-addition-queries-ii/
