// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [C]")
	testCases := [][2]string{
		{
			`4
			3
			0 3 7
			2 10 11
			2
			10 15
			11 16
			9
			12 16 90 195 1456 1569 3001 5237 19275
			13 199 200 260 9100 10000 10914 91066 5735533
			1
			0
			1000000000`,
			`2 7 1 
			1 1 
			1 183 1 60 7644 900 914 80152 5644467 
			1000000000 
			`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://codeforces.com/contest/1690/problem/C
