// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc248/submit?taskScreenName=abc248_c
// 对拍：https://atcoder.jp/contests/abc248/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc248_c&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`2 3 4`,
			`6`,
		},
		{
			`31 41 592`,
			`798416518`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc248/tasks/abc248_c
