// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc381/submit?taskScreenName=abc381_f
// 对拍：https://atcoder.jp/contests/abc381/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc381_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`7
			1 3 3 1 2 2 1`,
			`4`,
		},
		{
			`1
			20`,
			`0`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc381/tasks/abc381_f
