// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc158/submit?taskScreenName=arc158_a
// 对拍：https://atcoder.jp/contests/arc158/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc158_a&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [a]")
	testCases := [][2]string{
		{
			`4
			2 8 8
			1 1 1
			5 5 10
			10 100 1000`,
			`2
			0
			-1
			315`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc158/tasks/arc158_a
