// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_c(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, minTime, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-442/problems/find-the-minimum-amount-of-time-to-brew-potions/
// https://leetcode.cn/problems/find-the-minimum-amount-of-time-to-brew-potions/
