// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_c(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, maxSubarraySum, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-427/problems/maximum-subarray-sum-with-length-divisible-by-k/
// https://leetcode.cn/problems/maximum-subarray-sum-with-length-divisible-by-k/
