// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/agc021/submit?taskScreenName=agc021_d
// 对拍：https://atcoder.jp/contests/agc021/submissions?f.LanguageName=Go&f.Status=AC&f.Task=agc021_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`abcabcabc
			1`,
			`7`,
		},
		{
			`atcodergrandcontest
			3`,
			`15`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/agc021/tasks/agc021_d
