// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc129/submit?taskScreenName=abc129_e
// 对拍：https://atcoder.jp/contests/abc129/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc129_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`10`,
			`5`,
		},
		{
			`1111111111111111111`,
			`162261460`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc129/tasks/abc129_e
