// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [E]")
	testCases := [][2]string{
		{
			`6
			6 3
			3 2 7 1 4 8
			4 3
			2 1 5 6
			4 12
			0 0 0 0
			2 1
			1 1
			6 10
			2 0 0 5 9 4
			6 5
			5 3 8 6 3 2`,
			`8
			4
			0
			2
			1
			5
			`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://codeforces.com/contest/1690/problem/E
