// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc158/submit?taskScreenName=arc158_e
// 对拍：https://atcoder.jp/contests/arc158/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc158_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`1
			3
			5`,
			`24`,
		},
		{
			`2
			1 2
			3 4`,
			`76`,
		},
		{
			`5
			1 1000000000 1 1 1
			1 1 1 1000000000 1`,
			`66714886`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc158/tasks/arc158_e
