// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc127/submit?taskScreenName=abc127_e
// 对拍：https://atcoder.jp/contests/abc127/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc127_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`2 2 2`,
			`8`,
		},
		{
			`4 5 4`,
			`87210`,
		},
		{
			`100 100 5000`,
			`817260251`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc127/tasks/abc127_e
