// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc375/submit?taskScreenName=abc375_f
// 对拍：https://atcoder.jp/contests/abc375/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc375_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`3 3 5
			1 2 5
			1 3 10
			2 3 6
			2 1 3
			1 2
			2 1 3
			1 1
			2 1 3`,
			`10
			11
			-1`,
		},
		{
			`4 6 6
			2 3 1
			2 4 1
			3 4 1
			1 2 1
			1 3 1
			1 4 1
			1 4
			1 5
			1 6
			2 1 2
			2 1 3
			2 1 4`,
			`-1
			-1
			-1`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc375/tasks/abc375_f
