// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc162/submit?taskScreenName=abc162_f
// 对拍：https://atcoder.jp/contests/abc162/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc162_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		//{
		//	`6
		//	1 2 3 4 5 6`,
		//	`12`,
		//},
		//{
		//	`5
		//	-1000 -100 -10 0 10`,
		//	`0`,
		//},
		//{
		//	`10
		//	1000000000 1000000000 1000000000 1000000000 1000000000 1000000000 1000000000 1000000000 1000000000 1000000000`,
		//	`5000000000`,
		//},
		//{
		//	`27
		//	18 -28 18 28 -45 90 -45 23 -53 60 28 -74 -71 35 -26 -62 49 -77 57 24 -70 -93 69 -99 59 57 -49`,
		//	`295`,
		//},
		{
			`3
 			1 2 3`,
			`3`,
		},
	}
	codeforces.AssertEqualStringCase(t, runV2, testCases, 0)
}

// https://atcoder.jp/contests/abc162/tasks/abc162_f
