// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc321/submit?taskScreenName=abc321_f
// 对拍：https://atcoder.jp/contests/abc321/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc321_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`15 10
			+ 5
			+ 2
			+ 3
			- 2
			+ 5
			+ 10
			- 3
			+ 1
			+ 3
			+ 3
			- 5
			+ 1
			+ 7
			+ 4
			- 3`,
			`0
			0
			1
			0
			1
			2
			2
			2
			2
			2
			1
			3
			5
			8
			5`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc321/tasks/abc321_f
