// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc138/submit?taskScreenName=abc138_c
// 对拍：https://atcoder.jp/contests/abc138/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc138_c&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`2
			3 4`,
			`3.5`,
		},
		{
			`3
			500 300 200`,
			`375`,
		},
		{
			`5
			138 138 138 138 138`,
			`138`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc138/tasks/abc138_c
