// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc248/submit?taskScreenName=abc248_b
// 对拍：https://atcoder.jp/contests/abc248/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc248_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`1 4 2`,
			`2`,
		},
		{
			`7 7 10`,
			`0`,
		},
		{
			`31 415926 5`,
			`6`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc248/tasks/abc248_b
