// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [B2]")
	testCases := [][2]string{
		{
			`5
			2
			6 4
			3
			3 10 6
			4
			4 8 7 2
			5
			9 8 2 4 6
			12
			2 6 13 3 15 5 10 8 16 9 11 18`,
			`1
			2
			8
			16
			232
			`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://codeforces.com/contest/1827/problem/B2
