// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc238/submit?taskScreenName=abc238_d
// 对拍：https://atcoder.jp/contests/abc238/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc238_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`2
			1 8
			4 2`,
			`Yes
			No`,
		},
		{
			`4
			201408139683277485 381410962404666524
			360288799186493714 788806911317182736
			18999951915747344 451273909320288229
			962424162689761932 1097438793187620758`,
			`No
			Yes
			Yes
			No`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc238/tasks/abc238_d
