// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc301/submit?taskScreenName=abc301_e
// 对拍：https://atcoder.jp/contests/abc301/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc301_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`3 3 5
			S.G
			o#o
			.#.`,
			`1`,
		},
		{
			`3 3 1
			S.G
			.#o
			o#.`,
			`-1`,
		},
		{
			`5 10 2000000
			S.o..ooo..
			..o..o.o..
			..o..ooo..
			..o..o.o..
			..o..ooo.G`,
			`18`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc301/tasks/abc301_e
