// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_a(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, maxGoodNumber, "a.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-418/problems/maximum-possible-number-by-binary-concatenation/
// https://leetcode.cn/problems/maximum-possible-number-by-binary-concatenation/
