// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/dp/submit?taskScreenName=dp_z
// 对拍：https://atcoder.jp/contests/dp/submissions?f.LanguageName=Go&f.Status=AC&f.Task=dp_z&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [z]")
	testCases := [][2]string{
		{
			`5 6
			1 2 3 4 5`,
			`20`,
		},
		{
			`2 1000000000000
			500000 1000000`,
			`1250000000000`,
		},
		{
			`8 5
			1 3 4 5 10 11 12 13`,
			`62`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/dp/tasks/dp_z
