// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc301/submit?taskScreenName=abc301_a
// 对拍：https://atcoder.jp/contests/abc301/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc301_a&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [a]")
	testCases := [][2]string{
		{
			`5
			TTAAT`,
			`T`,
		},
		{
			`6
			ATTATA`,
			`T`,
		},
		{
			`1
			A`,
			`A`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc301/tasks/abc301_a
