// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc087/submit?taskScreenName=arc087_b
// 对拍：https://atcoder.jp/contests/arc087/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc087_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`FTFFTFFF
			4 2`,
			`Yes`,
		},
		{
			`FTFFTFFF
			-2 -2`,
			`Yes`,
		},
		{
			`FF
			1 0`,
			`No`,
		},
		{
			`TF
			1 0`,
			`No`,
		},
		{
			`FFTTFF
			0 0`,
			`Yes`,
		},
		{
			`TTTT
			1 0`,
			`No`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/arc087/tasks/arc087_b
