// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc202/submit?taskScreenName=abc202_d
// 对拍：https://atcoder.jp/contests/abc202/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc202_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		//{
		//	`2 2 4`,
		//	`baab`,
		//},
		{
			`30 30 118264581564861424`,
			`bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc202/tasks/abc202_d
