// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc298/submit?taskScreenName=abc298_c
// 对拍：https://atcoder.jp/contests/abc298/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc298_c&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`5
			8
			1 1 1
			1 2 4
			1 1 4
			2 4
			1 1 4
			2 4
			3 1
			3 2`,
			`1 2
			1 1 2
			1 4
			4`,
		},
		{
			`1
			5
			1 1 1
			1 2 1
			1 200000 1
			2 1
			3 200000`,
			`1 2 200000
			1`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc298/tasks/abc298_c
