// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc155/submit?taskScreenName=abc155_a
// 对拍：https://atcoder.jp/contests/abc155/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc155_a&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [a]")
	testCases := [][2]string{
		{
			`5 7 5`,
			`Yes`,
		},
		{
			`4 4 4`,
			`No`,
		},
		{
			`4 9 6`,
			`No`,
		},
		{
			`3 3 4`,
			`Yes`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc155/tasks/abc155_a
