// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_d(t *testing.T) {
	targetCaseNum := 3
	if err := leetcode.RunLeetCodeFuncWithFile(t, countOperationsToEmptyArray, "d.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-103/problems/make-array-empty/
// https://leetcode.cn/problems/make-array-empty/
