// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc300/submit?taskScreenName=abc300_f
// 对拍：https://atcoder.jp/contests/abc300/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc300_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`10 1 2
			ooxxooooox`,
			`9`,
		},
		{
			`5 3 4
			oxxox`,
			`8`,
		},
		{
			`30 1000000000 9982443530
			oxoxooxoxoxooxoxooxxxoxxxooxox`,
			`19964887064`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc300/tasks/abc300_f
