// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [D]")
	testCases := [][2]string{
		{
			`5
			2
			1
			3
			1 1
			4
			1 2 3
			7
			1 2 3 2 5 2
			10
			1 2 2 4 5 5 7 8 9`,
			`0
			0 1
			0 1 0
			0 1 0 1 2 3
			0 1 2 1 0 1 0 1 2`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://codeforces.com/contest/1827/problem/D
