// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, isPossibleToRearrange, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-425/problems/rearrange-k-substrings-to-form-target-string/
// https://leetcode.cn/problems/rearrange-k-substrings-to-form-target-string/
