// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc149/submit?taskScreenName=arc149_b
// 对拍：https://atcoder.jp/contests/arc149/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc149_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`5
			5 2 1 4 3
			3 1 2 5 4`,
			`8`,
		},
		{
			`5
			1 2 3 4 5
			1 2 3 4 5`,
			`10`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/arc149/tasks/arc149_b
