// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_a(t *testing.T) {
	targetCaseNum := 0 // -1
	if err := leetcode.RunLeetCodeFuncWithFile(t, findTheLongestBalancedSubstring, "b.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-339/problems/find-the-longest-balanced-substring-of-a-binary-string/
// https://leetcode.cn/problems/find-the-longest-balanced-substring-of-a-binary-string/
