// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc233/submit?taskScreenName=abc233_d
// 对拍：https://atcoder.jp/contests/abc233/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc233_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`6 5
			8 -3 5 7 0 -4`,
			`3`,
		},
		{
			`2 -1000000000000000
			1000000000 -1000000000`,
			`0`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc233/tasks/abc233_d
