// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc189/submit?taskScreenName=arc189_d
// 对拍：https://atcoder.jp/contests/arc189/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc189_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`6
			4 13 2 3 2 6`,
			`4 30 2 13 2 13`,
		},
		{
			`12
			22 25 61 10 21 37 2 14 5 8 6 24`,
			`22 47 235 10 31 235 2 235 5 235 6 235`,
		},
		{
			`3
			1 1 1`,
			`1 1 1`,
		},
		{
			`4
			1 2 1 2`,
			`1 6 1 6`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc189/tasks/arc189_d
