// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc398/submit?taskScreenName=abc398_f
// 对拍：https://atcoder.jp/contests/abc398/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc398_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`ABC`,
			`ABCBA`,
		},
		{
			`Z`,
			`Z`,
		},
		{
			`TREE`,
			`TREERT`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc398/tasks/abc398_f
