// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc299/submit?taskScreenName=abc299_g
// 对拍：https://atcoder.jp/contests/abc299/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc299_g&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [g]")
	testCases := [][2]string{
		{
			`4 3
			2 3 1 3`,
			`2 1 3`,
		},
		{
			`4 4
			2 3 1 4`,
			`2 3 1 4`,
		},
		{
			`20 10
			6 3 8 5 8 10 9 3 6 1 8 3 3 7 4 7 2 7 8 5`,
			`3 5 8 10 9 6 1 4 2 7`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc299/tasks/abc299_g
