// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc355/submit?taskScreenName=abc355_F
// 对拍：https://atcoder.jp/contests/abc355/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc355_F&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [F]")
	testCases := [][2]string{
		{
			`4 4
			1 2 6
			2 3 5
			2 4 4
			1 3 3
			1 2 3
			1 4 10
			3 4 1`,
			`12
			10
			10
			7`,
		},
		{
			`8 6
			1 8 8
			1 6 10
			1 5 8
			2 6 6
			6 7 6
			1 3 9
			2 4 7
			1 3 4
			1 6 7
			3 4 6
			1 5 1
			7 8 4
			3 5 3`,
			`49
			46
			45
			38
			34
			33`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc355/tasks/abc355_F
