// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_c(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, maxFrequency, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-143/problems/maximum-frequency-of-an-element-after-performing-operations-ii/
// https://leetcode.cn/problems/maximum-frequency-of-an-element-after-performing-operations-ii/
