// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	targetCaseNum := -1 // -1
	if err := leetcode.RunLeetCodeFuncWithFile(t, numberOfPairs, "b.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-123/problems/find-the-number-of-ways-to-place-people-i/
// https://leetcode.cn/problems/find-the-number-of-ways-to-place-people-i/
