// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc280/submit?taskScreenName=abc280_e
// 对拍：https://atcoder.jp/contests/abc280/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc280_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`3 10`,
			`229596204`,
		},
		{
			`5 100`,
			`3`,
		},
		{
			`280 59`,
			`567484387`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc280/tasks/abc280_e
