// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/diverta2019/submit?taskScreenName=diverta2019_d
// 对拍：https://atcoder.jp/contests/diverta2019/submissions?f.LanguageName=Go&f.Status=AC&f.Task=diverta2019_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`8`,
			`10`,
		},
		{
			`1000000000000`,
			`2499686339916`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/diverta2019/tasks/diverta2019_d
