// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`4
			5 2
			1 2
			2 3
			3 4
			2 5
			1 4
			5 2
			5 1
			1 2
			2 3
			3 4
			2 5
			1 5
			2 0
			1 2
			6 3
			1 2
			2 3
			3 4
			4 5
			5 6
			1 3
			2 5
			4 6`,
			`YES
			NO
			1 3
			NO
			1 2
			NO
			1 6`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://codeforces.com/contest/1827/problem/E
