// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc321/submit?taskScreenName=abc321_c
// 对拍：https://atcoder.jp/contests/abc321/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc321_c&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`15`,
			`32`,
		},
		{
			`321`,
			`9610`,
		},
		{
			`777`,
			`983210`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc321/tasks/abc321_c
