// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc159/submit?taskScreenName=abc159_d
// 对拍：https://atcoder.jp/contests/abc159/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc159_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`5
			1 1 2 1 2`,
			`2
			2
			3
			2
			3`,
		},
		{
			`4
			1 2 3 4`,
			`0
			0
			0
			0`,
		},
		{
			`5
			3 3 3 3 3`,
			`6
			6
			6
			6
			6`,
		},
		{
			`8
			1 2 1 4 2 1 4 1`,
			`5
			7
			5
			7
			7
			5
			7
			5`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc159/tasks/abc159_d
