// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc245/submit?taskScreenName=abc245_g
// 对拍：https://atcoder.jp/contests/abc245/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc245_g&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [g]")
	testCases := [][2]string{
		{
			`4 4 2 2
			1 1 2 2
			2 3
			1 2 15
			2 3 30
			3 4 40
			1 4 10`,
			`45 30 30 25`,
		},
		{
			`3 1 3 1
			1 2 3
			1
			1 2 1000000000`,
			`-1 1000000000 -1`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc245/tasks/abc245_g
