// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc277/submit?taskScreenName=abc277_e
// 对拍：https://atcoder.jp/contests/abc277/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc277_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`5 5 2
			1 3 0
			2 3 1
			5 4 1
			2 1 1
			1 4 0
			3 4`,
			`5`,
		},
		{
			`4 4 2
			4 3 0
			1 2 1
			1 2 0
			2 1 1
			2 4`,
			`-1`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc277/tasks/abc277_e
