// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_d(t *testing.T) {
	targetCaseNum := 0 // -1
	if err := leetcode.RunLeetCodeFuncWithFile(t, minEdgeReversals, "d.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-113/problems/minimum-edge-reversals-so-every-node-is-reachable/
// https://leetcode.cn/problems/minimum-edge-reversals-so-every-node-is-reachable/
