// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc308/submit?taskScreenName=abc308_d
// 对拍：https://atcoder.jp/contests/abc308/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc308_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`2 3
			sns
			euk`,
			`Yes`,
		},
		{
			`2 2
			ab
			cd`,
			`No`,
		},
		{
			`5 7
			skunsek
			nukesnu
			ukeseku
			nsnnesn
			uekukku`,
			`Yes`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc308/tasks/abc308_d
