// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [F]")
	testCases := [][2]string{
		{
			`5
			5
			5 2 1 4 3
			4
			2 1 4 3
			1
			1
			8
			7 5 8 1 4 2 6 3
			10
			1 4 5 3 7 8 9 2 10 6`,
			`15 15 11 10 9 9 
			10 8 8 7 7 
			1 1 
			36 30 25 19 15 13 12 9 9 
			55 55 41 35 35 25 22 22 19 17 17 
			`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://codeforces.com/contest/1827/problem/F
