// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc214/submit?taskScreenName=abc214_d
// 对拍：https://atcoder.jp/contests/abc214/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc214_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`3
			1 2 10
			2 3 20`,
			`50`,
		},
		{
			`5
			1 2 1
			2 3 2
			4 2 5
			3 5 14`,
			`76`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc214/tasks/abc214_d
