// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc138/submit?taskScreenName=abc138_b
// 对拍：https://atcoder.jp/contests/abc138/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc138_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`2
			10 30`,
			`7.5`,
		},
		{
			`3
			200 200 200`,
			`66.66666666666667`,
		},
		{
			`1
			1000`,
			`1000`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc138/tasks/abc138_b
