// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_c(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, countOfPairs, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-410/problems/find-the-count-of-monotonic-pairs-i/
// https://leetcode.cn/problems/find-the-count-of-monotonic-pairs-i/
