// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc071/submit?taskScreenName=arc071_b
// 对拍：https://atcoder.jp/contests/arc071/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc071_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`3 3
			1 3 4
			1 3 6`,
			`60`,
		},
		{
			`6 5
			-790013317 -192321079 95834122 418379342 586260100 802780784
			-253230108 193944314 363756450 712662868 735867677`,
			`835067060`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc071/tasks/arc071_b
