// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc290/submit?taskScreenName=abc290_e
// 对拍：https://atcoder.jp/contests/abc290/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc290_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`5
			5 2 1 2 2`,
			`9`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc290/tasks/abc290_e
