// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc308/submit?taskScreenName=abc308_c
// 对拍：https://atcoder.jp/contests/abc308/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc308_c&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`3
			1 3
			3 1
			2 2`,
			`2 3 1`,
		},
		{
			`2
			1 3
			2 6`,
			`1 2`,
		},
		{
			`4
			999999999 1000000000
			333333333 999999999
			1000000000 999999997
			999999998 1000000000`,
			`3 1 4 2`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc308/tasks/abc308_c
