// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, unmarkedSumArray, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-126/problems/mark-elements-on-array-by-performing-queries/
// https://leetcode.cn/problems/mark-elements-on-array-by-performing-queries/
