// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_a(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, maxSum, "a.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-441/problems/maximum-unique-subarray-sum-after-deletion/
// https://leetcode.cn/problems/maximum-unique-subarray-sum-after-deletion/
