// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/agc005/submit?taskScreenName=agc005_b
// 对拍：https://atcoder.jp/contests/agc005/submissions?f.LanguageName=Go&f.Status=AC&f.Task=agc005_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`3
			2 1 3`,
			`9`,
		},
		{
			`4
			1 3 2 4`,
			`19`,
		},
		{
			`8
			5 4 8 1 2 6 7 3`,
			`85`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/agc005/tasks/agc005_b
