// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc371/submit?taskScreenName=abc371_e
// 对拍：https://atcoder.jp/contests/abc371/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc371_e&orderBy=source_length
func Test_e(t *testing.T) {
	testCases := [][2]string{
		{
			`3
			1 2 2`,
			`8`,
		},
		{
			`9
			5 4 2 2 3 2 4 4 1`,
			`111`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc371/tasks/abc371_e
