// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc373/submit?taskScreenName=abc373_f
// 对拍：https://atcoder.jp/contests/abc373/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc373_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`2 10
			3 4
			3 2`,
			`5`,
		},
		{
			`3 6
			1 4
			2 3
			2 7`,
			`14`,
		},
		{
			`1 10
			1 7`,
			`12`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc373/tasks/abc373_f
