// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc155/submit?taskScreenName=abc155_b
// 对拍：https://atcoder.jp/contests/abc155/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc155_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`5
			6 7 9 10 31`,
			`APPROVED`,
		},
		{
			`3
			28 27 24`,
			`DENIED`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc155/tasks/abc155_b
