// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc110/submit?taskScreenName=arc110_f
// 对拍：https://atcoder.jp/contests/arc110/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc110_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`8
			7 1 2 6 4 0 5 3`,
			`4
			6
			0
			3
			0`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc110/tasks/arc110_f
