// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc196/submit?taskScreenName=abc196_f
// 对拍：https://atcoder.jp/contests/abc196/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc196_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`0001
			101`,
			`1`,
		},
		{
			`0101010
			1010101`,
			`7`,
		},
		{
			`10101000010011011110
			0010011111`,
			`1`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc196/tasks/abc196_f
