// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc308/submit?taskScreenName=abc308_a
// 对拍：https://atcoder.jp/contests/abc308/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc308_a&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [a]")
	testCases := [][2]string{
		{
			`125 175 250 300 400 525 600 650`,
			`Yes`,
		},
		{
			`100 250 300 400 325 575 625 675`,
			`No`,
		},
		{
			`0 23 24 145 301 413 631 632`,
			`No`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc308/tasks/abc308_a
