// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc248/submit?taskScreenName=abc248_d
// 对拍：https://atcoder.jp/contests/abc248/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc248_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`5
			3 1 4 1 5
			4
			1 5 1
			2 4 3
			1 5 2
			1 3 3`,
			`2
			0
			0
			1`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc248/tasks/abc248_d
