// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [D]")
	testCases := [][2]string{
		{
			`4
			1
			1
			1
			2`,
			`18`,
		},
		{
			`6
			1
			3
			2
			3
			5
			2
			`,
			`150`,
		},
		{
			`20
			3
			1
			4
			1
			5
			9
			2
			6
			5
			3
			5
			8
			9
			7
			9
			3
			2
			3
			8
			4
			`,
			`563038556`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/tenka1-2019/tasks/tenka1_2019_d
