// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, maxPossibleScore, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-414/problems/maximize-score-of-numbers-in-ranges/
// https://leetcode.cn/problems/maximize-score-of-numbers-in-ranges/
