// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [C]")
	testCases := [][2]string{
		{
			`6
			6
			abaaba
			1
			a
			2
			aa
			6
			abcdef
			12
			accabccbacca
			6
			abbaaa`,
			`3
			0
			1
			0
			14
			6
			`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://codeforces.com/contest/1827/problem/C
