// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc158/submit?taskScreenName=arc158_d
// 对拍：https://atcoder.jp/contests/arc158/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc158_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`3
			1 7
			2 7
			10 998244353`,
			`1 4 6
			1 2 5
			20380119 21549656 279594297`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc158/tasks/arc158_d
