// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc360/submit?taskScreenName=abc360_g
// 对拍：https://atcoder.jp/contests/abc360/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc360_g&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [g]")
	testCases := [][2]string{
		{
			`4
			3 2 2 4`,
			`3`,
		},
		{
			`5
			4 5 3 6 7`,
			`4`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc360/tasks/abc360_g
