// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc356/submit?taskScreenName=abc356_e
// 对拍：https://atcoder.jp/contests/abc356/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc356_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`3
			3 1 4`,
			`8`,
		},
		{
			`6
			2 7 1 8 2 8`,
			`53`,
		},
		{
			`12
			3 31 314 3141 31415 314159 2 27 271 2718 27182 271828`,
			`592622`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc356/tasks/abc356_e
