// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc312/submit?taskScreenName=abc312_f
// 对拍：https://atcoder.jp/contests/abc312/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc312_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`8 4
			0 6
			0 6
			1 3
			1 5
			1 15
			2 1
			2 10
			2 100`,
			`27`,
		},
		{
			`5 5
			1 5
			1 5
			1 5
			1 5
			1 5`,
			`0`,
		},
		{
			`12 6
			2 2
			0 1
			0 9
			1 3
			1 5
			1 3
			0 4
			2 1
			1 8
			2 1
			0 1
			0 4`,
			`30`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc312/tasks/abc312_f
