// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc158/submit?taskScreenName=arc158_f
// 对拍：https://atcoder.jp/contests/arc158/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc158_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`3 2 3
			74 42 54
			42 54 74`,
			`5`,
		},
		{
			`2 1 1
			2 3
			3 2`,
			`0`,
		},
		{
			`5 100 4
			0 12 34 56 78
			0 12 34 56 78`,
			`982924732`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc158/tasks/arc158_f
