// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc075/submit?taskScreenName=arc075_c
// 对拍：https://atcoder.jp/contests/arc075/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc075_c&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`3 6
			7
			5
			7`,
			`5`,
		},
		{
			`1 2
			1`,
			`0`,
		},
		{
			`7 26
			10
			20
			30
			40
			30
			20
			10`,
			`13`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/arc075/tasks/arc075_c
