// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc194/submit?taskScreenName=abc194_a
// 对拍：https://atcoder.jp/contests/abc194/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc194_a&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [a]")
	testCases := [][2]string{
		{
			`10 8`,
			`1`,
		},
		{
			`1 2`,
			`3`,
		},
		{
			`0 0`,
			`4`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc194/tasks/abc194_a
