// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc378/submit?taskScreenName=abc378_e
// 对拍：https://atcoder.jp/contests/abc378/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc378_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`3 4
			2 5 0`,
			`10`,
		},
		{
			`10 100
			320 578 244 604 145 839 156 857 556 400`,
			`2736`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc378/tasks/abc378_e
