// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc133/submit?taskScreenName=abc133_e
// 对拍：https://atcoder.jp/contests/abc133/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc133_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`4 3
			1 2
			2 3
			3 4`,
			`6`,
		},
		{
			`5 4
			1 2
			1 3
			1 4
			4 5`,
			`48`,
		},
		{
			`16 22
			12 1
			3 1
			4 16
			7 12
			6 2
			2 15
			5 16
			14 16
			10 11
			3 10
			3 13
			8 6
			16 8
			9 12
			4 3`,
			`271414432`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc133/tasks/abc133_e
