// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_c(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, minTimeToReach, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-422/problems/find-minimum-time-to-reach-last-room-ii/
// https://leetcode.cn/problems/find-minimum-time-to-reach-last-room-ii/
