// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc339/submit?taskScreenName=abc339_e
// 对拍：https://atcoder.jp/contests/abc339/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc339_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`4 2
			3 5 1 2`,
			`3`,
		},
		{
			`5 10
			10 20 100 110 120`,
			`3`,
		},
		{
			`11 7
			21 10 3 19 28 12 11 3 3 15 16`,
			`6`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc339/tasks/abc339_e
