// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc147/submit?taskScreenName=arc147_c
// 对拍：https://atcoder.jp/contests/arc147/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc147_c&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`3
			1 3
			2 4
			5 6`,
			`4`,
		},
		{
			`3
			1 1
			1 1
			1 1`,
			`0`,
		},
		{
			`6
			1 5
			2 4
			1 1
			4 4
			3 6
			3 3`,
			`15`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc147/tasks/arc147_c
