// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, numberOfSubstrings, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-420/problems/count-substrings-with-k-frequency-characters-i/
// https://leetcode.cn/problems/count-substrings-with-k-frequency-characters-i
