// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, maxDistance, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-435/problems/maximum-manhattan-distance-after-k-changes/
// https://leetcode.cn/problems/maximum-manhattan-distance-after-k-changes/
