// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc110/submit?taskScreenName=arc110_d
// 对拍：https://atcoder.jp/contests/arc110/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc110_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`3 5
			1 2 1`,
			`8`,
		},
		{
			`10 998244353
			31 41 59 26 53 58 97 93 23 84`,
			`642612171`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc110/tasks/arc110_d
