// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc136/submit?taskScreenName=arc136_d
// 对拍：https://atcoder.jp/contests/arc136/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc136_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`4
			4 8 12 90`,
			`3`,
		},
		{
			`20
			313923 246114 271842 371982 284858 10674 532090 593483 185123 364245 665161 241644 604914 645577 410849 387586 732231 952593 249651 36908`,
			`6`,
		},
		{
			`5
			1 1 1 1 1`,
			`10`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc136/tasks/arc136_d
