// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc392/submit?taskScreenName=abc392_g
// 对拍：https://atcoder.jp/contests/abc392/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc392_g&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [g]")
	testCases := [][2]string{
		{
			`5
			8 3 1 5 2`,
			`3`,
		},
		{
			`7
			300000 100000 499998 499999 200000 400000 500000`,
			`5`,
		},
		{
			`10
			13 1 16 15 12 4 7 10 2 19`,
			`10`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc392/tasks/abc392_g
