// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc295/submit?taskScreenName=abc295_d
// 对拍：https://atcoder.jp/contests/abc295/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc295_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`20230322`,
			`4`,
		},
		{
			`0112223333444445555556666666777777778888888889999999999`,
			`185`,
		},
		{
			`3141592653589793238462643383279502884197169399375105820974944`,
			`9`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc295/tasks/abc295_d
