// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc155/submit?taskScreenName=abc155_c
// 对拍：https://atcoder.jp/contests/abc155/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc155_c&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`7
			beat
			vet
			beet
			bed
			vet
			bet
			beet`,
			`beet
			vet`,
		},
		{
			`8
			buffalo
			buffalo
			buffalo
			buffalo
			buffalo
			buffalo
			buffalo
			buffalo`,
			`buffalo`,
		},
		{
			`7
			bass
			bass
			kick
			kick
			bass
			kick
			kick`,
			`kick`,
		},
		{
			`4
			ushi
			tapu
			nichia
			kun`,
			`kun
			nichia
			tapu
			ushi`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc155/tasks/abc155_c
