// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc088/submit?taskScreenName=arc088_b
// 对拍：https://atcoder.jp/contests/arc088/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc088_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`010`,
			`2`,
		},
		{
			`100000000`,
			`8`,
		},
		{
			`00001111`,
			`4`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/arc088/tasks/arc088_b
