// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	targetCaseNum := 0 // -1
	if err := leetcode.RunLeetCodeFuncWithFile(t, isReachableAtTime, "b.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-362/problems/determine-if-a-cell-is-reachable-at-a-given-time/
// https://leetcode.cn/problems/determine-if-a-cell-is-reachable-at-a-given-time/
