// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_a(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, getSmallestString, "a.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-406/problems/lexicographically-smallest-string-after-a-swap/
// https://leetcode.cn/problems/lexicographically-smallest-string-after-a-swap/
