// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [B]")
	testCases := [][2]string{
		{
			`4 2
			2 5 2 5
			`,
			`12`,
		},
		{
			`8 4
			9 1 8 2 7 5 6 4
			`,
			`32`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/dwacon5th-prelims/tasks/dwacon5th_prelims_b
