// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc110/submit?taskScreenName=arc110_b
// 对拍：https://atcoder.jp/contests/arc110/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc110_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`4
			1011`,
			`9999999999`,
		},
		{
			`22
			1011011011011011011011`,
			`9999999993`,
		},
		{
			`1
			1`,
			`20000000000`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc110/tasks/arc110_b
