// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_d(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, numberOfStableArrays, "d.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-129/problems/find-all-possible-stable-binary-arrays-ii/
// https://leetcode.cn/problems/find-all-possible-stable-binary-arrays-ii/
