// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, valueAfterKSeconds, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-401/problems/find-the-n-th-value-after-k-seconds/
// https://leetcode.cn/problems/find-the-n-th-value-after-k-seconds/
