// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc248/submit?taskScreenName=abc248_a
// 对拍：https://atcoder.jp/contests/abc248/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc248_a&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [a]")
	testCases := [][2]string{
		{
			`023456789`,
			`1`,
		},
		{
			`459230781`,
			`6`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc248/tasks/abc248_a
