// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc146/submit?taskScreenName=abc146_e
// 对拍：https://atcoder.jp/contests/abc146/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc146_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`5 4
			1 4 2 3 5`,
			`4`,
		},
		{
			`8 4
			4 2 4 2 4 2 4 2`,
			`7`,
		},
		{
			`10 7
			14 15 92 65 35 89 79 32 38 46`,
			`8`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc146/tasks/abc146_e
