// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc392/submit?taskScreenName=abc392_e
// 对拍：https://atcoder.jp/contests/abc392/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc392_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`4 5
			1 1
			1 2
			2 1
			3 4
			4 4`,
			`1
			1 1 3`,
		},
		{
			`4 3
			3 4
			4 1
			1 2`,
			`0`,
		},
		{
			`5 4
			3 3
			3 3
			3 3
			3 3`,
			`4
			1 3 5
			2 3 4
			3 3 2
			4 3 1`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc392/tasks/abc392_e
