// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_c(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, maxOperations, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-407/problems/maximum-number-of-operations-to-move-ones-to-the-end/
// https://leetcode.cn/problems/maximum-number-of-operations-to-move-ones-to-the-end/
