// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc288/submit?taskScreenName=abc288_e
// 对拍：https://atcoder.jp/contests/abc288/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc288_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`5 2
			3 1 4 1 5
			9 2 6 5 3
			3 5`,
			`17`,
		},
		{
			`20 8
			29 27 79 27 30 4 93 89 44 88 70 75 96 3 78 39 97 12 53 62
			32 38 84 49 93 53 26 13 25 2 76 32 42 34 18 77 14 67 88 12
			1 3 4 5 8 14 16 20`,
			`533`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc288/tasks/abc288_e
