// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc137/submit?taskScreenName=arc137_a
// 对拍：https://atcoder.jp/contests/arc137/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc137_a&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [a]")
	testCases := [][2]string{
		{
			`2 4`,
			`1`,
		},
		{
			`14 21`,
			`5`,
		},
		{
			`1 100`,
			`99`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc137/tasks/arc137_a
