// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc359/submit?taskScreenName=abc359_d
// 对拍：https://atcoder.jp/contests/abc359/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc359_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`7 4
			AB?A?BA`,
			`1`,
		},
		{
			`40 7
			????????????????????????????????????????`,
			`116295436`,
		},
		{
			`15 5
			ABABA??????????`,
			`0`,
		},
		{
			`40 8
			?A?B??B?B?AA?A?B??B?A???B?BB?B???BA??BAA`,
			`259240`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc359/tasks/abc359_d
