// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc398/submit?taskScreenName=abc398_d
// 对拍：https://atcoder.jp/contests/abc398/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc398_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`6 -2 1
			NNEEWS`,
			`001010`,
		},
		{
			`10 1 2
			NEESESWEES`,
			`0001101011`,
		},
		{
			`20 -1 -2
			WWNNWSWEWNSWWENSNWWN`,
			`00100111111000101111`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc398/tasks/abc398_d
