// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc281/submit?taskScreenName=abc281_d
// 对拍：https://atcoder.jp/contests/abc281/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc281_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`4 2 2
			1 2 3 4`,
			`6`,
		},
		{
			`3 1 2
			1 3 5`,
			`-1`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc281/tasks/abc281_d
