// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc300/submit?taskScreenName=abc300_e
// 对拍：https://atcoder.jp/contests/abc300/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc300_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`6`,
			`239578645`,
		},
		{
			`7`,
			`0`,
		},
		{
			`300`,
			`183676961`,
		},
		{
			`979552051200000000`,
			`812376310`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc300/tasks/abc300_e
