// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc340/submit?taskScreenName=abc340_f
// 对拍：https://atcoder.jp/contests/abc340/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc340_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`3 5`,
			`1 1`,
		},
		{
			`-2 0`,
			`0 1`,
		},
		{
			`8752654402832944 -6857065241301125`,
			`-1`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc340/tasks/abc340_f
