// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [B]")
	testCases := [][2]string{
		{
			`6
			4
			3 5 4 1
			1 3 2 0
			3
			1 2 1
			0 1 0
			4
			5 3 7 2
			1 1 1 1
			5
			1 2 3 4 5
			1 2 3 4 6
			1
			8
			0
			1
			4
			6`,
			`YES
			YES
			NO
			NO
			YES
			NO
			`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://codeforces.com/contest/1690/problem/B
