// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc208/submit?taskScreenName=abc208_e
// 对拍：https://atcoder.jp/contests/abc208/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc208_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`13 2`,
			`5`,
		},
		{
			`100 80`,
			`99`,
		},
		{
			`1000000000000000000 1000000000`,
			`841103275147365677`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc208/tasks/abc208_e
