// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc173/submit?taskScreenName=abc173_e
// 对拍：https://atcoder.jp/contests/abc173/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc173_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`4 2
			1 2 -3 -4`,
			`12`,
		},
		{
			`4 3
			-1 -2 -3 -4`,
			`1000000001`,
		},
		{
			`2 1
			-1 1000000000`,
			`1000000000`,
		},
		{
			`10 10
			1000000000 100000000 10000000 1000000 100000 10000 1000 100 10 1`,
			`999983200`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc173/tasks/abc173_e
