// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/agc015/submit?taskScreenName=agc015_c
// 对拍：https://atcoder.jp/contests/agc015/submissions?f.LanguageName=Go&f.Status=AC&f.Task=agc015_c&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`3 4 4
			1101
			0110
			1101
			1 1 3 4
			1 1 3 1
			2 2 3 4
			1 2 2 4`,
			`3
			2
			2
			2`,
		},
		{
			`5 5 6
			11010
			01110
			10101
			11101
			01010
			1 1 5 5
			1 2 4 5
			2 3 3 4
			3 3 3 3
			3 1 3 5
			1 1 3 4`,
			`3
			2
			1
			1
			3
			2`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/agc015/tasks/agc015_c
