// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc288/submit?taskScreenName=abc288_h
// 对拍：https://atcoder.jp/contests/abc288/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc288_h&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [h]")
	testCases := [][2]string{
		{
			`3 3 2`,
			`5`,
		},
		{
			`200 900606388 317329110`,
			`788002104`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc288/tasks/abc288_h
