// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/practice2/submit?taskScreenName=practice2_j
// 对拍：https://atcoder.jp/contests/practice2/submissions?f.LanguageName=Go&f.Status=AC&f.Task=practice2_j&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [j]")
	testCases := [][2]string{
		{
			`5 5
			1 2 3 2 1
			2 1 5
			3 2 3
			1 3 1
			2 2 4
			3 1 3`,
			`3
			3
			2
			6`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/practice2/tasks/practice2_j
