// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc384/submit?taskScreenName=abc384_f
// 对拍：https://atcoder.jp/contests/abc384/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc384_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`2
			4 8`,
			`5`,
		},
		{
			`3
			51 44 63`,
			`384`,
		},
		{
			`8
			577752 258461 183221 889769 278633 577212 392309 326001`,
			`20241214`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc384/tasks/abc384_f
