// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	targetCaseNum := -1 // -1
	if err := leetcode.RunLeetCodeFuncWithFile(t, lastNonEmptyString, "b.txt", targetCaseNum); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-124/problems/apply-operations-to-make-string-empty/
// https://leetcode.cn/problems/apply-operations-to-make-string-empty/
