// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc301/submit?taskScreenName=abc301_b
// 对拍：https://atcoder.jp/contests/abc301/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc301_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`4
			2 5 1 2`,
			`2 3 4 5 4 3 2 1 2`,
		},
		{
			`6
			3 4 5 6 5 4`,
			`3 4 5 6 5 4`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc301/tasks/abc301_b
