// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc298/submit?taskScreenName=abc298_b
// 对拍：https://atcoder.jp/contests/abc298/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc298_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`3
			0 1 1
			1 0 0
			0 1 0
			1 1 0
			0 0 1
			1 1 1`,
			`Yes`,
		},
		{
			`2
			0 0
			0 0
			1 1
			1 1`,
			`Yes`,
		},
		{
			`5
			0 0 1 1 0
			1 0 0 1 0
			0 0 1 0 1
			0 1 0 1 0
			0 1 0 0 1
			1 1 0 0 1
			0 1 1 1 0
			0 0 1 1 1
			1 0 1 0 1
			1 1 0 1 0`,
			`No`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc298/tasks/abc298_b
