// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc308/submit?taskScreenName=abc308_b
// 对拍：https://atcoder.jp/contests/abc308/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc308_b&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [b]")
	testCases := [][2]string{
		{
			`3 2
			red green blue
			blue red
			800 1600 2800`,
			`5200`,
		},
		{
			`3 2
			code queen atcoder
			king queen
			10 1 1`,
			`21`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc308/tasks/abc308_b
