// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc117/submit?taskScreenName=abc117_d
// 对拍：https://atcoder.jp/contests/abc117/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc117_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`3 7
			1 6 3`,
			`14`,
		},
		{
			`4 9
			7 4 0 3`,
			`46`,
		},
		{
			`1 0
			1000000000000`,
			`1000000000000`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc117/tasks/abc117_d
