// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc309/submit?taskScreenName=abc309_f
// 对拍：https://atcoder.jp/contests/abc309/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc309_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`3
			19 8 22
			10 24 12
			15 25 11`,
			`Yes`,
		},
		{
			`3
			19 8 22
			10 25 12
			15 24 11`,
			`No`,
		},
		{
			`2
			1 1 2
			1 2 2`,
			`No`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc309/tasks/abc309_f
