// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/code-festival-2016-qualc/submissions
// 对拍：https://atcoder.jp/contests/code-festival-2016-qualc/submissions?f.LanguageName=Go&f.Status=AC&f.Task=diverta2019_a&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [c]")
	testCases := [][2]string{
		{
			`5
			1 3 3 3 3
			3 3 2 2 2
			`,
			`4`,
		},
		{
			`5
			1 1 1 2 2
			3 2 1 1 1
			`,
			`0`,
		},
		{
			`10
			1 3776 3776 8848 8848 8848 8848 8848 8848 8848
			8848 8848 8848 8848 8848 8848 8848 8848 3776 5
			`,
			`884111967`,
		},
		{
			`1
			17
			17
			`,
			`1`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/code-festival-2016-qualc/tasks/codefestival_2016_qualC_c
