// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_c(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, minMaxWeight, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-432/problems/minimize-the-maximum-edge-weight-of-graph/
// https://leetcode.cn/problems/minimize-the-maximum-edge-weight-of-graph/
