// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, longestPalindrome, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-443/problems/longest-palindrome-after-substring-concatenation-i/
// https://leetcode.cn/problems/longest-palindrome-after-substring-concatenation-i/
