// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/arc134/submit?taskScreenName=arc134_d
// 对拍：https://atcoder.jp/contests/arc134/submissions?f.LanguageName=Go&f.Status=AC&f.Task=arc134_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`3
			2 1 3 1 2 2`,
			`1 2`,
		},
		{
			`10
			38 38 80 62 62 67 38 78 74 52 53 77 59 83 74 63 80 61 68 55`,
			`38 38 38 52 53 77 80 55`,
		},
		{
			`12
			52 73 49 63 55 74 35 68 22 22 74 50 71 60 52 62 65 54 70 59 65 54 60 52`,
			`22 22 50 65 54 52`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/arc134/tasks/arc134_d
