// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, lengthAfterTransformations, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-421/problems/total-characters-in-string-after-transformations-i/
// https://leetcode.cn/problems/total-characters-in-string-after-transformations-i/
