// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_a(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, minBitwiseArray, "a.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-141/problems/construct-the-minimum-bitwise-array-i/
// https://leetcode.cn/problems/construct-the-minimum-bitwise-array-i/
