// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_a(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, maxDifference, "a.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-435/problems/maximum-difference-between-even-and-odd-frequency-i/
// https://leetcode.cn/problems/maximum-difference-between-even-and-odd-frequency-i/
