// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc391/submit?taskScreenName=abc391_g
// 对拍：https://atcoder.jp/contests/abc391/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc391_g&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [g]")
	testCases := [][2]string{
		{
			`2 2
			ab`,
			`576 99 1`,
		},
		{
			`3 4
			aaa`,
			`390625 62500 3750 101`,
		},
		{
			`7 50
			atcoder`,
			`309810541 226923474 392073062 146769908 221445233 435648037 862664208 238437587`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc391/tasks/abc391_g
