// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc342/submit?taskScreenName=abc342_d
// 对拍：https://atcoder.jp/contests/abc342/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc342_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`5
			0 3 2 8 12`,
			`6`,
		},
		{
			`8
			2 2 4 6 3 100 100 25`,
			`7`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc342/tasks/abc342_d
