// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_c(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, constructGridLayout, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-418/problems/construct-2d-grid-matching-graph-layout/
// https://leetcode.cn/problems/construct-2d-grid-matching-graph-layout/
