// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_c(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, maxFreeTime, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-149/problems/reschedule-meetings-for-maximum-free-time-ii/
// https://leetcode.cn/problems/reschedule-meetings-for-maximum-free-time-ii/
