// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc308/submit?taskScreenName=abc308_e
// 对拍：https://atcoder.jp/contests/abc308/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc308_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`4
			1 1 0 2
			MEEX`,
			`3`,
		},
		{
			`3
			0 0 0
			XXX`,
			`0`,
		},
		{
			`15
			1 1 2 0 0 2 0 2 0 0 0 0 0 2 2
			EXMMXXXEMEXEXMM`,
			`13`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc308/tasks/abc308_e
