// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_a(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, minimumOperations, "a.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-429/problems/minimum-number-of-operations-to-make-elements-in-array-distinct/
// https://leetcode.cn/problems/minimum-number-of-operations-to-make-elements-in-array-distinct/
