// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, answerString, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-430/problems/find-the-lexicographically-largest-string-from-the-box-i/
// https://leetcode.cn/problems/find-the-lexicographically-largest-string-from-the-box-i/
