// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

func Test_run(t *testing.T) {
	t.Log("Current test is [F]")
	testCases := [][2]string{
		{
			`3
			5
			ababa
			3 4 5 2 1
			5
			ababa
			2 1 4 5 3
			10
			codeforces
			8 6 1 7 5 2 9 3 10 4`,
			`1
			6
			12
			`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://codeforces.com/contest/1690/problem/F
