// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc321/submit?taskScreenName=abc321_a
// 对拍：https://atcoder.jp/contests/abc321/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc321_a&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [a]")
	testCases := [][2]string{
		{
			`321`,
			`Yes`,
		},
		{
			`123`,
			`No`,
		},
		{
			`1`,
			`Yes`,
		},
		{
			`86411`,
			`No`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc321/tasks/abc321_a
