// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_b(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, getLargestOutlier, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/weekly-contest-426/problems/identify-the-largest-outlier-in-an-array/
// https://leetcode.cn/problems/identify-the-largest-outlier-in-an-array/
