// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc392/submit?taskScreenName=abc392_f
// 对拍：https://atcoder.jp/contests/abc392/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc392_f&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [f]")
	testCases := [][2]string{
		{
			`4
			1 1 2 1`,
			`4 2 3 1`,
		},
		{
			`5
			1 2 3 4 5`,
			`1 2 3 4 5`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc392/tasks/abc392_f
