// Code generated by template/gen/leetcode/generator_test.go
package main

import (
	"problems/testutil/leetcode"
	"testing"
)

func Test_a(t *testing.T) {
	if err := leetcode.RunLeetCodeFuncWithFile(t, minimumOperations, "a.txt", 0); err != nil {
		t.Fatal(err)
	}
}

// https://leetcode.cn/contest/biweekly-contest-133/problems/find-minimum-operations-to-make-all-elements-divisible-by-three/
// https://leetcode.cn/problems/find-minimum-operations-to-make-all-elements-divisible-by-three/
