// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc376/submit?taskScreenName=abc376_e
// 对拍：https://atcoder.jp/contests/abc376/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc376_e&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [e]")
	testCases := [][2]string{
		{
			`3
			3 2
			3 7 6
			9 2 4
			5 3
			6 4 1 5 9
			8 6 5 1 7
			10 6
			61 95 61 57 69 49 46 47 14 43
			39 79 48 92 90 76 30 16 30 94`,
			`42
			60
			14579`,
		},
		
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}
// https://atcoder.jp/contests/abc376/tasks/abc376_e
