// Code generated by copypasta/gen/atcoder/generator_test.go
package main

import (
	"problems/testutil/codeforces"
	"testing"
)

// 提交：https://atcoder.jp/contests/abc301/submit?taskScreenName=abc301_d
// 对拍：https://atcoder.jp/contests/abc301/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc301_d&orderBy=source_length
func Test_run(t *testing.T) {
	t.Log("Current test is [d]")
	testCases := [][2]string{
		{
			`?0?
			2`,
			`1`,
		},
		{
			`101
			4`,
			`-1`,
		},
		{
			`?0?
			1000000000000000000`,
			`5`,
		},
	}
	codeforces.AssertEqualStringCase(t, run, testCases, 0)
}

// https://atcoder.jp/contests/abc301/tasks/abc301_d
